Refactor: refactor AmountExtractor
ultralab-by/real-time-billing pull request #1
Opened 2021-12-09 16:35 UTC by andreitsukanov

2021-12-09 18:56 UTC, emitskevich commented on src/main/java/com/zavod/utils/AmountExtractor.java
> +        : new BigDecimal(amountValue);
Did you change `BigDecimal.valueOf()` to `new BigDecimal()` intentionally? Behaviour inside is not the same.

2021-12-09 19:02 UTC, emitskevich commented on src/main/java/com/zavod/utils/AmountExtractor.java
>      }
Suggestion:
```
    if (amountString.length() > 0 && amount.compareTo(scaled) != 0) {
      logLoss(amount, scaled);
    }
```

2021-12-10 10:03 UTC, wardomski commented on src/main/java/com/zavod/utils/AmountExtractor.java
>      }
Applied

2021-12-10 10:03 UTC, wardomski commented on src/main/java/com/zavod/utils/AmountExtractor.java
> +        : new BigDecimal(amountValue);
Fixed

2021-12-14 17:11 UTC, emitskevich requested changes
Can you please provide tests for two public methods?

2022-02-06 13:08 UTC, emitskevich approved these changes

2022-02-06 13:09 UTC, merged